---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "mumbaiKeyPair"
    # vpc_subnet_id: default
    instance_type: t2.micro
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ec2_access_key}}" # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}" # From vault as defined
    network_interfaces:
      - assign_public_ip: true
    image_id: "{{ item.image }}"

  loop:
    - { image: "ami-0dee22c13ea7a9a67", name: "manage-node1" }
    - { image: "ami-0dee22c13ea7a9a67", name: "manage-node2" }
    # - { image: "ami-08bf489a05e916bbd", name: "manage-node3" }
